- hosts: cognos
  pre_tasks:
    - set_fact:
        machineType: "{{ operating_system }}"
  roles:
    - role: win-cognos-base
      when: operating_system == 'windows'
    - role: cognos-base
      when: operating_system == 'linux'

- hosts: cognos_dispatcher
  roles:
    - role: win-cognos-dispatcher
      when: operating_system == 'windows'
    - role: cognos-dispatcher
      when: operating_system == 'linux'

- hosts: cognos_gateway
  roles:
    - role: win-cognos-gateway
      when: operating_system == 'windows'
    - role: cognos-gateway
      when: operating_system == 'linux'